CREATE DATABASE BLINKIT;
USE BLINKIT;
SHOW TABLES;


SELECT * FROM BLINKIT_DATA ;
UPDATE BLINKIT_DATA
SET ITEM_FAT_CONTENT=
CASE 
WHEN ITEM_FAT_CONTENT IN ('LF','low Fat') then 'Low Fat'
WHEN ITEM_FAT_CONTENT= 'reg' then 'Regular'
ELSE ITEM_FAT_CONTENT
END;

SET SQL_SAFE_UPDATES=0;

# 1.TOTAL SALES
SELECT CAST(SUM(SALES)/1000000 AS DECIMAL(10,2)) AS TOTAL_SALES FROM BLINKIT_DATA;

# 2.TOTAL COUNT
SELECT COUNT(`ITEM TYPE`) FROM BLINKIT_DATA
WHERE `Outlet Establishment YEAR`=2022;

# 3.AVERAGE_SALES
SELECT CAST(AVG(SALES) AS DECIMAL(10,0)) FROM BLINKIT_DATA;

#AVERAGE RATING
SELECT CAST(AVG(RATING) AS DECIMAL(10,2)) FROM BLINKIT_DATA;

# 4.TOTAL SALES BY FAT CONTENT
SELECT CAST(SUM(SALES) AS DECIMAL(10,2)) AS TOTAL_SALES ,ITEM_FAT_CONTENT
 FROM BLINKIT_DATA
GROUP BY ITEM_FAT_CONTENT
ORDER BY ITEM_FAT_CONTENT;

# 5.TOTAL SALES BY ITEM TYPE
SELECT CAST(SUM(SALES) AS DECIMAL(10,2)) AS TOTAL_SALES ,`Item Type`
 FROM BLINKIT_DATA
GROUP BY `Item Type`
ORDER BY `Item Type`DESC;

# 6.TOTAL SALES BY OUTLET ESTABLISHMENT
SELECT CAST(SUM(SALES) AS DECIMAL(10,2)) AS TOTAL_SALES ,`Outlet Establishment Year`
 FROM BLINKIT_DATA
GROUP BY `Outlet Establishment Year`
ORDER BY `Outlet Establishment Year`DESC;

# 7.FAT BY OUTLET FOR TOTAL SALES
SELECT CAST(SUM(SALES) AS DECIMAL(10,2)) AS TOTAL_SALES ,ITEM_FAT_CONTENT,`Outlet Location Type`
 FROM BLINKIT_DATA
GROUP BY `Outlet Location Type`, ITEM_FAT_CONTENT 
ORDER BY `Outlet Location Type` DESC;

# 8.SALES BY OUTLET SIZE
SELECT OUTLET_SIZE, 
ROUND(SUM(Sales)*100/ SUM(SUM(Sales)) OVER(),2) AS PERCENTAGE FROM BLINKIT_DATA
GROUP BY OUTLET_SIZE
ORDER BY OUTLET_SIZE;

# 9.SALES BY OUTLET LOCATION
SELECT `Outlet Location Type`,ROUND(SUM(Sales),2) AS TOTALES_SALES
FROM BLINKIT_DATA
GROUP BY `Outlet Location Type`
ORDER BY TOTALES_SALES;

# TOTAL SALES,AVERAGE SALES,AVERAGE RATING,NO OF ITEMS BY OUTLET TYPE
SELECT `Outlet Type`,
CAST(SUM(SALES) AS DECIMAL(10,2)) AS TOTAL_SALES ,
 CAST(AVG(SALES) AS DECIMAL(10,0)) AS AVERAGE_SALES, 
CAST(AVG(RATING) AS DECIMAL(10,2)) AS AVERAGE_RATING,
COUNT(`ITEM TYPE`) AS NO_OF_ITEMS
FROM BLINKIT_DATA
GROUP BY `Outlet Type`
ORDER BY`Outlet Type`;
